sudo: required
dist: trusty

language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.2.2

cache:
  apt: true
  directories:
    - $HOME/.stack/
    - .stack-work/

before_install: mkdir -p $HOME/.local/bin
install:
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true
  - pip install --user --upgrade awscli

before_script: rm -rf .build
script: ./Shakefile.hs docker:travis

env:
  global:
    - PATH=$HOME/.local/bin:/opt/ghc/8.2.2/bin:$PATH
    - AWS_DEFAULT_REGION=us-west-2
    - secure: "fCKFbXd/kcL4+BzSy7WcB6CkvW1opuVnA6Xq72RjTzNh5IQK/5DdiKewpeESFiZvOhScnLKSF1qC6qq6b/uJLw3PNVBfI0IQHM9AKQbMat2tQ20VISr3dOU5xfijYe6mtGPNT4Kj7RxCfyvKCawMA5dczeyl9+uc0eDH81XLeB3kVbynfmqENskDYOOPy9n3e7hTdxWjEW6TC8qrBSINRdis5ZqzEmEGSGSieNFzR30INEd/4JrKfaSWZTGKerqQJ+aHT+ec657Lb7/sJ0gIK9ljhsG3X4Zs2/wCJBojMF5heIYxsHGlilWyaH5bPff2FGhkc3Gf5BJqTlHv91KhrXPSaS7127tqURVZ16UgmhPf6s7JdklEMbzsJ8SsavRnlXAkhM1wPY9xinTeD9sp/VJu/1993nwg+IPw/JIr1F2qkaZ/XxGUQgX+vuNuKi/aZoFDpD01ALn8h0NceoUQumNHGjz+Gx+0qVYsuoWSHTZRe4zuMBDsh+xoedRljVzO0IHnKJJnkVNSjyYiU/s+jw2nvFYpY8VTwy1qRw09ZJkLmu4Ar6voexRqpL3cGSFLavuzgsVNG9rqVz0+Jq8wPo8xLtWSulPKdaAuPh3NVjHfGOIWQqm8KlA9yoWiRvvfrsg5w9VRBgFrq/rXlyVe+zf5rqpo8QXWtF0HGfJdSyE="
    - secure: "ncGZoQCvViIZJSXUdvd76nMfyznS/0zwyeXZKw2rwkO7TT4Upqf663rRIDRU7CmJ5lQLmtO6m2R2ErIQNbdHKKl6Le3BycbAVBZbgtNmdMMPRrcsH8ajSBYLdY5QaRmRsxrtsgrPU7w9M0kzfzx5dlnAit/QzW/cWWCUfAjC8g6FTqO/q+GPit0GSc7GSNO/D0EWYj3TNOdqntiL3jvsniR0ZUWvI8Syopyvj1ApP9A7bTbKZ51GQI16wHqBItYQiTC8q2chql9gCgJX8rCcmftCybI9LAS2mO6U/U7lNvdXSv465YqoZvWPeVFzocpB7L9Gk4lp7bLo/siTWUhpuBYa9Z8DrB3O3WhGOTkqUnbH7NT167OunkE1GM3N5ac6SuB6QKLCuXQwzasFCEP4NJXtq6hCXX7GgSKFXNslUc2sfwUqoRvd5ZEWRYzkB3Ac/NayccWGgkJXDBaoScocJhsN96UgRMWDpDdZ8QPSyJG13xAeCGx2Ze9IuGPeWcLcZwfAS6L4yt+E1RYiR7ml0VhXS5iFEBJ07kpHVydQkUry0U38dI8rwU1NzRGbRevq07dbAth62hprDMVmpmSC1PZzIkBG7xsWd7hEjKJLXlDwwxp9fX+cKRn4+EF62nvd+HUdLT0rYVdLZToiB5g2DjXT0bhC6IsBqcawyJ/N/IY="
