- package:
  - name: wolf
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Network.AWS.Wolf.Types.Ctx
        - identifier:
          - HasAmazonCtx
          - MonadAmazon
          - _acCtx
          - _acEnv
          - _adcConfCtx
          - _adcEvents
          - _adcPlan
          - _ascConfCtx
          - _ascPrefix
          - _awcConfCtx
          - _awcQueue
          - _ccConf
          - _ccStatsCtx
          - acCtx
          - acEnv
          - adcConfCtx
          - amazonCtx
          - amazonDecisionCtx
          - amazonStoreCtx
          - amazonWorkCtx
          - ascConfCtx
          - awcConfCtx
          - ccStatsCtx
      - module:
        - name: Network.AWS.Wolf.Types.Product
        - identifier:
          - _cBucket
          - _cDomain
          - _cPrefix
          - _cRunUid
          - _pStart
          - _pTasks
          - _tName
          - _tQueue
          - _tVersion
          - cRunUid

